"""empty message

Revision ID: 17821cb1ee29
Revises: bc4d3775390a
Create Date: 2019-11-07 11:47:27.412553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17821cb1ee29'
down_revision = 'bc4d3775390a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk_reports_campaigns1_idx', table_name='reports')
    op.drop_index('fk_reports_persons1_idx', table_name='reports')
    op.drop_table('reports')
    op.add_column('campaigns', sa.Column('Clients_User', mysql.INTEGER(display_width=11), nullable=False))
    op.add_column('campaigns', sa.Column('Log-in_User', sa.String(length=45), nullable=False))
    op.add_column('campaigns', sa.Column('status_id', mysql.INTEGER(display_width=11), nullable=False))
    op.add_column('campaigns', sa.Column('users_id', mysql.INTEGER(display_width=11), nullable=False))
    op.create_index(op.f('ix_campaigns_Clients_User'), 'campaigns', ['Clients_User'], unique=False)
    op.create_index(op.f('ix_campaigns_status_id'), 'campaigns', ['status_id'], unique=False)
    op.create_index(op.f('ix_campaigns_users_id'), 'campaigns', ['users_id'], unique=False)
    op.create_index(op.f('ix_campaigns_villages_id'), 'campaigns', ['villages_id'], unique=False)
    op.drop_index('fk_Campaigns_villages1_idx', table_name='campaigns')
    op.drop_index('fk_campaigns_users1_idx', table_name='campaigns')
    op.drop_index('fk_campaigns_users2_idx', table_name='campaigns')
    op.drop_constraint('fk_campaigns_users2', 'campaigns', type_='foreignkey')
    op.drop_constraint('fk_campaigns_users1', 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'users', ['users_id'], ['id'])
    op.create_foreign_key(None, 'campaigns', 'clients', ['Clients_User'], ['id'])
    op.create_foreign_key(None, 'campaigns', 'status', ['status_id'], ['id'])
    op.drop_column('campaigns', 'admin_id')
    op.drop_column('campaigns', 'budget')
    op.drop_column('campaigns', 'endDate')
    op.drop_column('campaigns', 'client_id')
    op.alter_column('clients', 'nombre',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('clients', 'users_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index(op.f('ix_clients_users_id'), 'clients', ['users_id'], unique=False)
    op.drop_index('fk_clients_users1_idx', table_name='clients')
    op.create_index(op.f('ix_contacts_Persons_id'), 'contacts', ['Persons_id'], unique=False)
    op.create_index(op.f('ix_contacts_typeContact_id'), 'contacts', ['typeContact_id'], unique=False)
    op.drop_index('fk_contacts_Persons1_idx', table_name='contacts')
    op.drop_index('fk_contacts_typeContact1_idx', table_name='contacts')
    op.create_index(op.f('ix_families_Persons_id'), 'families', ['Persons_id'], unique=False)
    op.create_index(op.f('ix_families_Relative_id'), 'families', ['Relative_id'], unique=False)
    op.create_index(op.f('ix_families_typesRelatives_id'), 'families', ['typesRelatives_id'], unique=False)
    op.drop_index('fk_families_Persons1_idx', table_name='families')
    op.drop_index('fk_families_Persons2_idx', table_name='families')
    op.drop_index('fk_families_typesRelatives1_idx', table_name='families')
    op.alter_column('persons', 'villages_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index(op.f('ix_persons_villages_id'), 'persons', ['villages_id'], unique=False)
    op.drop_index('fk_Persons_villages1_idx', table_name='persons')
    op.create_index(op.f('ix_regions_countries_id'), 'regions', ['countries_id'], unique=False)
    op.drop_index('fk_regions_countries1_idx', table_name='regions')
    op.create_index(op.f('ix_users_roles_id'), 'users', ['roles_id'], unique=False)
    op.drop_index('fk_Users_roles1_idx', table_name='users')
    op.drop_index('fk_cities_regions1_idx', table_name='villages')
    op.drop_constraint('fk_cities_regions1', 'villages', type_='foreignkey')
    op.drop_column('villages', 'village')
    op.drop_column('villages', 'regions_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('villages', sa.Column('regions_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('villages', sa.Column('village', mysql.VARCHAR(length=45), nullable=True))
    op.create_foreign_key('fk_cities_regions1', 'villages', 'regions', ['regions_id'], ['id'])
    op.create_index('fk_cities_regions1_idx', 'villages', ['regions_id'], unique=False)
    op.create_index('fk_Users_roles1_idx', 'users', ['roles_id'], unique=False)
    op.drop_index(op.f('ix_users_roles_id'), table_name='users')
    op.create_index('fk_regions_countries1_idx', 'regions', ['countries_id'], unique=False)
    op.drop_index(op.f('ix_regions_countries_id'), table_name='regions')
    op.create_index('fk_Persons_villages1_idx', 'persons', ['villages_id'], unique=False)
    op.drop_index(op.f('ix_persons_villages_id'), table_name='persons')
    op.alter_column('persons', 'villages_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index('fk_families_typesRelatives1_idx', 'families', ['typesRelatives_id'], unique=False)
    op.create_index('fk_families_Persons2_idx', 'families', ['Relative_id'], unique=False)
    op.create_index('fk_families_Persons1_idx', 'families', ['Persons_id'], unique=False)
    op.drop_index(op.f('ix_families_typesRelatives_id'), table_name='families')
    op.drop_index(op.f('ix_families_Relative_id'), table_name='families')
    op.drop_index(op.f('ix_families_Persons_id'), table_name='families')
    op.create_index('fk_contacts_typeContact1_idx', 'contacts', ['typeContact_id'], unique=False)
    op.create_index('fk_contacts_Persons1_idx', 'contacts', ['Persons_id'], unique=False)
    op.drop_index(op.f('ix_contacts_typeContact_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_Persons_id'), table_name='contacts')
    op.create_index('fk_clients_users1_idx', 'clients', ['users_id'], unique=False)
    op.drop_index(op.f('ix_clients_users_id'), table_name='clients')
    op.alter_column('clients', 'users_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('clients', 'nombre',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.add_column('campaigns', sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('endDate', sa.DATE(), nullable=True))
    op.add_column('campaigns', sa.Column('budget', mysql.DECIMAL(precision=10, scale=0), nullable=False))
    op.add_column('campaigns', sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key('fk_campaigns_users1', 'campaigns', 'users', ['admin_id'], ['id'])
    op.create_foreign_key('fk_campaigns_users2', 'campaigns', 'users', ['client_id'], ['id'])
    op.create_index('fk_campaigns_users2_idx', 'campaigns', ['client_id'], unique=False)
    op.create_index('fk_campaigns_users1_idx', 'campaigns', ['admin_id'], unique=False)
    op.create_index('fk_Campaigns_villages1_idx', 'campaigns', ['villages_id'], unique=False)
    op.drop_index(op.f('ix_campaigns_villages_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_users_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_Clients_User'), table_name='campaigns')
    op.drop_column('campaigns', 'users_id')
    op.drop_column('campaigns', 'status_id')
    op.drop_column('campaigns', 'Log-in_User')
    op.drop_column('campaigns', 'Clients_User')
    op.create_table('reports',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('persons_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('campaigns_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('email_sent', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('sms_sent', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaigns_id'], ['campaigns.id'], name='fk_reports_campaigns1'),
    sa.ForeignKeyConstraint(['persons_id'], ['persons.id'], name='fk_reports_persons1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_reports_persons1_idx', 'reports', ['persons_id'], unique=False)
    op.create_index('fk_reports_campaigns1_idx', 'reports', ['campaigns_id'], unique=False)
    # ### end Alembic commands ###
